Repository djay/covidthailand, pull requests merged in 2021-10, with the labels that each got.

#89 Jbarratt/issue 88 error in situation pui
  covid_data.py
  tests/situation_pui_en/situation-no626-260964.2021-09-26.json
  tests/test_scraping.py
Labels: bug

#101 Adds myself to the README
  README.md
Labels: documentation

#94 Remove extra zero from fomatter #86
  utils_pandas.py
Labels: bug, enhancement

#105 convert string to numeric comparison for date check in vac_manuf_given
  covid_data.py
Labels: bug
